"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { parseHistoricalImport, historicalCsvTemplate, type ImportRow } from "@/lib/historical-import-format";
import { previewHistoricalImport, commitHistoricalImport } from "@/app/actions/historical-import";
import { useFeedback, useFeedbackState } from "@/components/FeedbackProvider";
type Choice={id:number;name:string;code?:string};
type Mapping={products:Record<string,number>;operators:Record<string,number>;machines:Record<string,number>};
type Preview=Extract<Awaited<ReturnType<typeof previewHistoricalImport>>,{ok:true}>;
export function HistoricalImport({products,operators,machines}:{products:Choice[];operators:Choice[];machines:Choice[]}){
 const router=useRouter(),notify=useFeedback();const [uploadVersion,setUploadVersion]=useState(0);const [content,setContent]=useState(''),[name,setName]=useState(''),[rows,setRows]=useState<ImportRow[]>([]),[mapping,setMapping]=useState<Mapping>({products:{},operators:{},machines:{}}),[preview,setPreview]=useState<Preview|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useFeedbackState('error');
 const form=()=>{const fd=new FormData();fd.set('content',content);fd.set('fileName',name);fd.set('mapping',JSON.stringify(mapping));return fd;};
 const change=(group:keyof Mapping,key:string,id:string)=>{setMapping(m=>({...m,[group]:{...m[group],[key]:Number(id)}}));setPreview(null);setConfirmed(false);};
 const groups=[['products','Produtos','productKey','productId',products],['operators','Operadores','operatorKey','operatorId',operators],['machines','Máquinas','machineKey','machineId',machines]] as const;
 return <div className="form-stack"><section className="panel form-stack"><h2>1. Escolher o ficheiro</h2><p>Importe JSON de folhas de turno (versão 1, folha única ou lista de folhas) ou CSV. Até 500 produções / 1 MB por ficheiro. PDFs e fotografias devem ser convertidos em dados antes da importação.</p>
 <button className="btn secondary" type="button" onClick={()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+historicalCsvTemplate],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='modelo-historico-sodilave.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Descarregar modelo CSV</button>
 <label>Ficheiro histórico<input key={uploadVersion} type="file" accept=".json,.csv,application/json,text/csv" disabled={busy} onChange={async e=>{setPreview(null);setConfirmed(false);setRows([]);setContent('');setError('');const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('O ficheiro pode ter até 1 MB.');const text=await file.text(),parsed=parseHistoricalImport(text);setName(file.name);setContent(text);setRows(parsed);setMapping({products:{},operators:{},machines:{}});}catch(e){setError(e instanceof Error?e.message:'Não foi possível ler o ficheiro.');}}}/></label>
 {rows.length>0&&<p>{rows.length} produção(ões) lida(s). Confirme as associações abaixo; nenhum registo foi ainda importado.</p>}
 </section>
 {rows.length>0&&<section className="panel form-stack"><h2>2. Associar os dados à aplicação</h2><p>Selecione os artigos e operadores correspondentes ao texto das folhas. São incluídos os registos inativos para permitir recuperar o histórico. Os códigos de lote antigos podem repetir-se.</p>
 {groups.map(([group,title,key,id,choices])=><section key={group}><h3>{title}</h3><div className="two-col">{Array.from(new Set(rows.map(r=>r[key]))).map(label=>{const row=rows.find(r=>r[key]===label)!;const fallback=row[id]??(group==='machines'?choices.find(c=>c.code===label.replace(/^M(?:AQ(?:UINA)?)?\s*/i,''))?.id:undefined);return <label key={label} style={{minWidth:0}}>Na folha: {label}<select style={{minWidth:0,maxWidth:'100%'}} disabled={busy} value={mapping[group][label]??fallback??''} onChange={e=>change(group,label,e.target.value)}><option value="">Selecione a correspondência</option>{choices.map(c=><option key={c.id} value={c.id}>{c.code?c.code+' — ':''}{c.name}</option>)}</select></label>;})}</div></section>)}
 <button className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');setPreview(null);setConfirmed(false);try{const result=await previewHistoricalImport(form());if(result.ok)setPreview(result);else setError(result.message);}catch{setError('Não foi possível validar o ficheiro.');}finally{setBusy(false);}}}>{busy?'A validar…':'Pré-visualizar importação'}</button>
 </section>}
 {preview&&<section className="panel form-stack"><h2>3. Rever e importar</h2><p><strong>{preview.newCount}</strong> novas produções · <strong>{preview.duplicateCount}</strong> já importadas (ignoradas) · <strong>{preview.errors}</strong> erro(s).</p>
 <div className="responsive-table"><table><thead><tr><th>Linha / data</th><th>Turno / máquina</th><th>Produto / operador</th><th>Lote</th><th>Quantidade / unidade</th><th>Validação</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.index}><td>{r.index} · {r.date}</td><td>{r.shift} · {r.machine}</td><td>{r.product}<br/>{r.operator}</td><td>{r.lot}</td><td>{r.quantity} {r.unit}<br/>{r.units} artigos/embalagem</td><td>{r.errors.map((e,i)=><p className="alert error" key={'e'+i}>{e}</p>)}{r.warnings.map((w,i)=><p key={'w'+i}>{w}</p>)}{r.duplicate?'Já importada':!r.errors.length?'Pronta':''}</td></tr>)}</tbody></table></div>
 <p className="notice">Estes registos entram no histórico e nos contadores das datas originais. Não criam stock disponível, não têm posição em armazém e não descontam MPs atuais. Testes ausentes ficam como “Não realizado”. O ficheiro original, incluindo observações e leituras antigas, fica conservado para consulta.</p>
 <label className="check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Revi datas, turnos, quantidades, unidades por embalagem, operadores e lotes.</label>
 <button className="btn primary" disabled={busy||!confirmed||preview.errors>0||preview.newCount===0} onClick={async()=>{setBusy(true);setError('');const fd=form();fd.set('confirmed','yes');fd.set('previewHash',preview.hash);try{const result=await commitHistoricalImport(fd);if(!result.ok){setError(result.message);return;}notify('success',`${result.created} produção(ões) importada(s); ${result.skipped} repetida(s) ignorada(s).`);setPreview(null);setRows([]);setContent('');setConfirmed(false);setUploadVersion(v=>v+1);router.refresh();}catch{setError('Não foi possível confirmar a importação. Pré-visualize novamente para verificar os registos já importados.');}finally{setBusy(false);}}}>{busy?'A importar…':'Confirmar importação histórica'}</button>
 </section>}
 {error&&<p className="alert error" role="alert">{error}</p>}</div>;
}
