import { FeedbackForm } from "@/components/FeedbackForm";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { PageIntro } from "@/components/PageIntro";
import { changeMachineLotConfig, closeCommercialLot, createCommercialLot } from "@/app/actions/lots";

type CommercialLotRow={id:number;code:string;productId:number;productName:string;status:string;notes:string|null;openedAt:Date;closedAt:Date|null;createdBy:string;materials:string|null;productionCount:bigint};
type ConfigRow={machineId:number;machineCode:string;majorLetter:string;minorLetter:string;updatedAt:Date;updatedBy:string|null};
type HistoryRow={id:number;machineCode:string;previousCode:string;newCode:string;changeType:string;reason:string;changedBy:string;effectiveAt:Date};

export default async function Page(){
 const user=await requireUser();
 const canManage=user.role==="ADMIN"||(user.role==="PRODUCTION_MANAGER"&&user.name.trim().toLowerCase()==="luís");
 const [products,rawMaterials,machines,lots,configs,history]=await Promise.all([
  db.product.findMany({where:{active:true},orderBy:{name:"asc"}}),
  db.rawMaterial.findMany({where:{active:true},orderBy:{name:"asc"}}),
  db.machine.findMany({where:{active:true},orderBy:{code:"asc"}}),
  db.$queryRaw<CommercialLotRow[]>`SELECT cl.id,cl.code,cl.productId,p.name productName,cl.status,cl.notes,cl.openedAt,cl.closedAt,u.name createdBy,GROUP_CONCAT(CONCAT(rm.name,' ',FORMAT(clm.percentage,3),'%') ORDER BY rm.name SEPARATOR ' · ') materials,COUNT(DISTINCT pla.productionId) productionCount FROM CommercialLot cl JOIN Product p ON p.id=cl.productId JOIN User u ON u.id=cl.createdById LEFT JOIN CommercialLotMaterial clm ON clm.commercialLotId=cl.id LEFT JOIN RawMaterial rm ON rm.id=clm.rawMaterialId LEFT JOIN ProductionLotAssociation pla ON pla.commercialLotId=cl.id GROUP BY cl.id ORDER BY cl.openedAt DESC,cl.id DESC`,
  db.$queryRaw<ConfigRow[]>`SELECT mlc.machineId,m.code machineCode,mlc.majorLetter,mlc.minorLetter,mlc.updatedAt,u.name updatedBy FROM MachineLotConfig mlc JOIN Machine m ON m.id=mlc.machineId LEFT JOIN User u ON u.id=mlc.updatedById ORDER BY m.code`,
  db.$queryRaw<HistoryRow[]>`SELECT h.id,m.code machineCode,CONCAT(h.previousMajor,h.previousMinor) previousCode,CONCAT(h.newMajor,h.newMinor) newCode,h.changeType,h.reason,u.name changedBy,h.effectiveAt FROM MachineLotConfigHistory h JOIN Machine m ON m.id=h.machineId JOIN User u ON u.id=h.changedById ORDER BY h.effectiveAt DESC,h.id DESC LIMIT 200`
 ]);
 return <><PageIntro title="Lotes comerciais e controlo interno" subtitle="Gerir lotes enviados ao cliente e o histórico das letras de controlo de cada máquina."/>
 {canManage&&<section className="panel form-stack"><h2>Criar lote comercial</h2><p className="muted">O código é criado automaticamente no formato L{String(new Date().getFullYear()).slice(-2)}001. Só pode existir um lote comercial ativo por produto.</p><FeedbackForm action={createCommercialLot} className="form-stack"><label>Produto<select name="productId" required><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></label><section className="subpanel"><h3>Mistura autorizada</h3>{Array.from({length:5},(_,i)=><div className="two-col" key={i}><label>Matéria-prima {i+1}<select name={`rawMaterialId_${i}`}><option value="">Não utilizar</option>{rawMaterials.map(r=><option key={r.id} value={r.id}>{r.code} — {r.name}</option>)}</select></label><label>Percentagem<input name={`percentage_${i}`} type="number" min="0" max="100" step="0.001"/></label></div>)}</section><label>Observações<textarea name="notes" placeholder="Critérios, cliente, encomenda ou outras notas."/></label><button className="btn primary">Criar lote comercial</button></FeedbackForm></section>}
 <section className="panel"><h2>Histórico de lotes comerciais</h2>{lots.length===0?<p className="empty-state">Ainda não existem lotes comerciais.</p>:<div className="responsive-table"><table><thead><tr><th>Código</th><th>Produto</th><th>Mistura</th><th>Estado</th><th>Abertura</th><th>Produções</th><th>Criado por</th><th>Ação</th></tr></thead><tbody>{lots.map(l=><tr key={l.id}><td><strong>{l.code}</strong></td><td>{l.productName}</td><td>{l.materials||"—"}</td><td>{l.status==="ACTIVE"?"Ativo":"Fechado"}</td><td>{new Date(l.openedAt).toLocaleString("pt-PT")}</td><td>{Number(l.productionCount)}</td><td>{l.createdBy}</td><td>{canManage&&l.status==="ACTIVE"?<FeedbackForm action={closeCommercialLot}><input type="hidden" name="id" value={l.id}/><button className="btn secondary">Fechar lote</button></FeedbackForm>:"—"}</td></tr>)}</tbody></table></div>}</section>
 <section className="panel form-stack"><h2>Configuração do controlo interno por máquina</h2><div className="responsive-table"><table><thead><tr><th>Máquina</th><th>Letras atuais</th><th>Última alteração</th><th>Alterado por</th></tr></thead><tbody>{configs.map(c=><tr key={c.machineId}><td>Máquina {c.machineCode}</td><td><strong>{c.majorLetter}{c.minorLetter}</strong></td><td>{new Date(c.updatedAt).toLocaleString("pt-PT")}</td><td>{c.updatedBy||"Inicial"}</td></tr>)}</tbody></table></div>{canManage&&<FeedbackForm action={changeMachineLotConfig} className="form-stack subpanel"><h3>Registar alteração</h3><div className="two-col"><label>Máquina<select name="machineId" required><option value="">Selecione</option>{machines.map(m=><option key={m.id} value={m.id}>Máquina {m.code}</option>)}</select></label><label>Tipo de alteração<select name="changeType" required><option value="MAJOR">Alteração maior — avança a primeira letra e reinicia a segunda em A</option><option value="MINOR">Afinação menor — avança a segunda letra</option></select></label></div><label>Motivo<textarea name="reason" required placeholder="Produto, molde, matéria-prima, mistura, afinação ou outra alteração que justifica o novo código."/></label><button className="btn primary">Registar e atualizar letras</button></FeedbackForm>}</section>
 <section className="panel"><h2>Histórico de alterações das letras</h2>{history.length===0?<p className="empty-state">Ainda não existem alterações.</p>:<div className="responsive-table"><table><thead><tr><th>Data</th><th>Máquina</th><th>Anterior</th><th>Novo</th><th>Tipo</th><th>Motivo</th><th>Utilizador</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{new Date(h.effectiveAt).toLocaleString("pt-PT")}</td><td>{h.machineCode}</td><td>{h.previousCode}</td><td><strong>{h.newCode}</strong></td><td>{h.changeType==="MAJOR"?"Alteração maior":"Afinação menor"}</td><td>{h.reason}</td><td>{h.changedBy}</td></tr>)}</tbody></table></div>}</section></>;
}
