ALTER TABLE `Production` ADD COLUMN `producedKg` DECIMAL(12,3) NULL, ADD COLUMN `productionColor` VARCHAR(80) NULL, ADD COLUMN `capPackaging` VARCHAR(8) NULL;
INSERT IGNORE INTO StorageLocation (warehouseCode,warehouseName,zoneType,rowNumber,columnNumber,code,active)
SELECT w.code,w.name,'PALLET',r.n,c.n,CONCAT('P-',CHAR(64+c.n),r.n),1
FROM (SELECT 'W1' code,'Armazém Sede' name UNION ALL SELECT 'W2','Armazém Zona Industrial') w
CROSS JOIN (SELECT 1 AS n UNION ALL SELECT 2 AS n UNION ALL SELECT 3 AS n UNION ALL SELECT 4 AS n UNION ALL SELECT 5 AS n UNION ALL SELECT 6 AS n UNION ALL SELECT 7 AS n UNION ALL SELECT 8 AS n UNION ALL SELECT 9 AS n UNION ALL SELECT 10 AS n) r CROSS JOIN (SELECT 1 AS n UNION ALL SELECT 2 AS n UNION ALL SELECT 3 AS n UNION ALL SELECT 4 AS n UNION ALL SELECT 5 AS n UNION ALL SELECT 6 AS n UNION ALL SELECT 7 AS n) c
WHERE NOT EXISTS (SELECT 1 FROM StorageLocation l WHERE l.warehouseCode=w.code AND l.code=CONCAT('P-',CHAR(64+c.n),r.n));
