import { FeedbackForm } from "@/components/FeedbackForm";
import { db } from "@/lib/db";
import { requireReadAccess } from "@/lib/auth";
import { PageIntro } from "@/components/PageIntro";
import { createMaintenance, completeMaintenance } from "@/app/actions/maintenance";

const typeLabel:any={PREVENTIVE:"Preventiva",CORRECTIVE:"Corretiva",SCHEDULED:"Programada"};
const statusLabel:any={OPEN:"Em aberto",COMPLETED:"Concluída",CANCELLED:"Cancelada"};
export default async function Page(){const user=await requireReadAccess();const [machines,users,rows]=await Promise.all([db.machine.findMany({where:{active:true},orderBy:{code:"asc"}}),db.user.findMany({select:{id:true,name:true},where:{active:true},orderBy:{name:"asc"}}),db.maintenance.findMany({include:{machines:{include:{machine:true}},participants:{include:{user:true}},createdBy:true},orderBy:{performedAt:"desc"},take:100})]);return <><PageIntro title="Manutenções" subtitle="Registar intervenções preventivas, corretivas e programadas."/>{user.role!=="AUDITOR"&&<section className="panel form-stack"><h2>Novo relatório de manutenção</h2><FeedbackForm action={createMaintenance} className="form-stack"><div className="two-col"><label>Tipo<select name="type" required><option value="PREVENTIVE">Preventiva</option><option value="CORRECTIVE">Corretiva</option><option value="SCHEDULED">Programada</option></select></label><label>Data e hora<input name="performedAt" type="datetime-local" required/></label></div><fieldset><legend>Máquinas intervencionadas</legend><div className="check-grid">{machines.map(m=><label className="check" key={m.id}><input type="checkbox" name="machineIds" value={m.id}/>{m.code} — {m.name}</label>)}</div></fieldset><fieldset><legend>Funcionários envolvidos</legend><div className="check-grid">{users.map(u=><label className="check" key={u.id}><input type="checkbox" name="participantIds" value={u.id}/>{u.name}</label>)}</div></fieldset><label>Relatório / observações<textarea name="observations" required placeholder="Descreva trabalhos realizados, peças substituídas, testes e resultado da intervenção."/></label><button className="btn primary">Criar manutenção</button></FeedbackForm></section>}<section className="panel"><h2>Histórico</h2>{rows.map(r=><article className="record-card" key={r.id}><div><strong>{typeLabel[r.type]} · {r.performedAt.toLocaleString("pt-PT")}</strong><p>{r.machines.map((x:any)=>x.machine.code).join(", ")} · {statusLabel[r.status]}</p><p>{r.observations}</p><small>Criada por {r.createdBy.name}. Envolvidos: {r.participants.map((x:any)=>x.user.name).join(", ")||"Não indicados"}</small></div>{user.role!=="AUDITOR"&&r.status==="OPEN"&&<FeedbackForm action={completeMaintenance}><input type="hidden" name="id" value={r.id}/><button className="btn primary">Concluir</button></FeedbackForm>}</article>)}</section></>}
